/* IMPORT THE DATA FROM THE CSV TO LOCAL SAS LIBRARY MYSASLIB
  USE DBMS OPTION AS CSV AND REPLACE IF DATASET WITH SAME NAME EXISTS
*/
PROC IMPORT OUT = MYSASLIB.ATHLETE_EVENTS
	DATAFILE='/folders/myfolders/SASUSER.v94/athlete_events.csv'
	DBMS=CSV REPLACE;
	*GET THE VARIABLE NAMES FROM THE CSV File;
	GETNAMES=YES;
	* DIRECT TO SAS THAT THE DATA STARTS AT ROW NO 2 IN EXCEL;
	DATAROW=2;
RUN;

/* CALCULATING THE MEANS USING THE PROC MEANS CODE 
*/
PROC MEANS DATA = MYSASLIB.ATHLETE_EVENTS;
	* SET TITLE FOR THE OUTPUT RESULTS;
	TITLE 'MEANS ON ALL THE VARIABLES';
RUN;

/* CALCULATING THE FREQUENCY ON VARIOUS VARIABLES
 USING THE FREQUENCY PROCEDURE
*/
PROC FREQ DATA = MYSASLIB.ATHLETE_EVENTS ORDER = FREQ;
	TABLES SEX YEAR SPORT MEDAL;
	TITLE "Frequency Procedure on Sex, Year, Sport and Medals won";
RUN;

PROC FREQ DATA = MYSASLIB.ATHLETE_EVENTS ORDER = FREQ;
	TABLES TEAM;
	TITLE "Frequency Procedure on Team from which the Athletes are participating";
RUN;
